### ISSUE TITLE
Fail to build app with "--link-to workshop/step4"

### ISSUE THREAD

**Issue by Honry** [MobileChromeApps/workshop-cca-eh#24]
Reproduce Steps
============================
1. Cordova CLI 5.0.0
2. cca v0.7.0
3. create EhApp
    $cca create EhApp --link-to workshop/step4
4. build EhApp
    $cd EhApp & cca run android

Error Log
============================
lei@lei-Studio-XPS-8000:~/work/workspace/cordova/cordova-4.0/google_plugins/EhApp$ cca run android
cca v0.7.0
Running command: /home/lei/work/workspace/cordova/cordova-4.0/google_plugins/EhApp/hooks/before_prepare/cca-check.js /home/lei/work/workspace/cordova/cordova-4.0/google_plugins/EhApp
Inject CSP for android
Running command: /home/lei/work/workspace/cordova/cordova-4.0/google_plugins/EhApp/platforms/android/cordova/run 
ANDROID_HOME=/home/lei/honry/adt-bundle-linux-x86-20140321/sdk
JAVA_HOME=/usr/lib/jvm/jdk1.6.0_34
WARNING : No target specified, deploying to device '08d33d28'.
Running: /home/lei/work/workspace/cordova/cordova-4.0/google_plugins/EhApp/platforms/android/gradlew cdvBuildDebug -b /home/lei/work/workspace/cordova/cordova-4.0/google_plugins/EhApp/platforms/android/build.gradle -PcdvBuildArch=arm -Dorg.gradle.daemon=true
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
 
FAILURE: Build failed with an exception.
 
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any version that matches com.android.support:support-v4:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/maven-metadata.xml
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified
   > Could not find any version that matches com.google.android.gms:play-services-gcm:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/google/android/gms/play-services-gcm/
     Required by:
         :android:unspecified
   > Could not find any version that matches com.google.android.gms:play-services-identity:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-identity/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-identity/
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/google/android/gms/play-services-identity/maven-metadata.xml
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/google/android/gms/play-services-identity/
     Required by:
         :android:unspecified
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 
BUILD FAILED

**Comment by agrieve** [comment]
Looks like probably you don't have the support repository downloaded into your android SDK. Open the SDK manager (from command line, type "`android`"). 

Under "Extras", Make sure you have "Android Support Repository" and "Google Repository" downloaded.

**Comment by Honry** [comment]
Wow, it works, very appreciate! @agrieve
