### ISSUE TITLE
How to test Eh?

### ISSUE THREAD

**Issue by Honry** [MobileChromeApps/workshop-cca-eh#25]
Hello

Greeting!!!
I come from Crosswalk QA, and very happy to see you use Crosswalk. 
We are going to test this interesting app to ensure everything goes well with Crosswalk.

All things goes smoothly except one confusion that I always see "You are all alone!" on my page. I have set up two devices with two google accounts which are contacts for each other. 

Did I miss something? Or is that expected result? Anyone could help provide the tutorial would be very appreciate.

Screenshot as below:
![eh1](https://cloud.githubusercontent.com/assets/3271201/7766423/a842c5e0-009b-11e5-8219-f52f28789ee5.png)
![eh2](https://cloud.githubusercontent.com/assets/3271201/7766424/a9edf19e-009b-11e5-8885-d90ae125fd03.png)

**Comment by agrieve** [comment]
Looks like the workshop had fallen into a little bit of disrepair :(.

I've just going through and fixed up a few things, and also added instructions for how to run your own server (which is now required).

Please try again by `git pull`ing, then look at the new instructions for running your own server:

https://github.com/MobileChromeApps/workshop-cca-eh/blob/master/docs/step2.md

**Comment by Honry** [comment]
hi, @agrieve 
Thanks for your feedback, do you mean set up my own server is a MUST step?

**Comment by agrieve** [comment]
Yes. It's a must step now. You can run it from a laptop though, doesn't need to be in the cloud.

**Comment by Honry** [comment]
Two devices with google accounts must to access the server which is ran on the host, and all of them should be able to access google service, am I right?

**Comment by agrieve** [comment]
I think that sounds right. you need two devices with logged in google accounts and access to the internet. and you need to run gcmServer/python/server.py on your machine

**Comment by Honry** [comment]
I will try it, thank you so much!

**Comment by Honry** [comment]
Sadly, I got some error when I try to run the server, error log as below:
```
C:\Users\wlin19\workshop-cca-eh\gcmServer>python python\server.py
Invalid debugflag given: socket  
DEBUG:  
DEBUG: Debug created for C:\Users\wlin19\workshop-cca-eh\gcmServer\python\xmpp\c
lient.py 
DEBUG:  flags defined: socket 
DEBUG: socket       start Plugging <xmpp.transports.TCPsocket instance at 0x0202 
DDA0> into <xmpp.client.Client instance at 0x0202DC88> 
DEBUG: socket       start Successfully connected to remote host ('gcm.googleapis 
.com', 5235) 
Traceback (most recent call last): 
  File "python\server.py", line 234, in <module> 
    main() 
  File "python\server.py", line 208, in main 
    client.connect(server=(SERVER, PORT), secure=1, use_srv=False) 
  File "C:\Users\wlin19\workshop-cca-eh\gcmServer\python\xmpp\client.py", line 2 
00, in connect 
    if not CommonClient.connect(self,server,proxy,secure,use_srv) or secure<>Non 
e and not secure: return self.connected 
  File "C:\Users\wlin19\workshop-cca-eh\gcmServer\python\xmpp\client.py", line 1 
78, in connect 
    transports.TLS().PlugIn(self,now=1) 
  File "C:\Users\wlin19\workshop-cca-eh\gcmServer\python\xmpp\transports.py", li 
ne 281, in PlugIn 
    if now: return self._startSSL() 
  File "C:\Users\wlin19\workshop-cca-eh\gcmServer\python\xmpp\transports.py", li 
ne 316, in _startSSL 
    tcpsock._sslIssuer = tcpsock._sslObj.issuer() 
AttributeError: '_ssl._SSLSocket' object has no attribute 'issuer'
``` 
When searched the error from Google, very luckily to find a similar issue from https://github.com/eventlet/eventlet/issues/124 and get the fix(https://raw.githubusercontent.com/freebsd/freebsd-ports/master/net-im/py-xmpppy/files/patch-xmpp-transports.py) which provided by the developer.
@agrieve, could you please check if this is a real issue and the fix is applicable?

**Comment by agrieve** [comment]
Seems to work in my env both with & without the patch, so I've applied it
:).

**Comment by Honry** [comment]
That's great! Thank you so much for your patient and kindly help, everything goes well now, I would like to close it.:)

**Comment by agrieve** [comment]
Awesome! Glad to hear you got it working, and thanks for find a bug (with a fix!)
