### ISSUE TITLE
Build fails with CCA v0.8.1

### ISSUE THREAD

**Issue by JohnRSim** [MobileChromeApps/workshop-cca-eh#26]
C:\work\svn\jsim\rig\mobile\tmp\EhApp>cca build android --debug
cca v0.8.1
## Running Cordova Command: plugin add cordova-plugin-whitelist@1.0.0
Fetching plugin "cordova-plugin-whitelist@1.0.0" via npm
Plugin "cordova-plugin-whitelist" already installed on android.
Running command: "C:\Program Files (x86)\nodejs\node.exe" C:\work\svn\jsim\rig\m
obile\tmp\EhApp\hooks\before_prepare\cca-check.js C:\work\svn\jsim\rig\mobile\tm
p\EhApp
## Inject CSP for android
ANDROID_HOME=C:\Users\John\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files (x86)\Java\jdk1.8.0_65
embedded
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be pro
vided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be pro
vided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be pro
vided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be pro
vided in the future.
org.xwalk:xwalk_core_library:15+
:preBuild
:compileArmv7DebugNdk UP-TO-DATE
:preArmv7DebugBuild
:checkArmv7DebugManifest
:preX86DebugBuild
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava
C:\work\svn\jsim\rig\mobile\tmp\EhApp\platforms\android\CordovaLib\src\org\apach
e\cordova\CordovaInterfaceImpl.java:191: error: cannot find symbol
        getActivity().requestPermissions(permissions, requestCode);
                     ^
  symbol:   method requestPermissions(String[],int)
  location: class Activity
C:\work\svn\jsim\rig\mobile\tmp\EhApp\platforms\android\CordovaLib\src\org\apach
e\cordova\CordovaInterfaceImpl.java:197: error: cannot find symbol
        getActivity().requestPermissions(permissions, requestCode);
                     ^
  symbol:   method requestPermissions(String[],int)
  location: class Activity
C:\work\svn\jsim\rig\mobile\tmp\EhApp\platforms\android\CordovaLib\src\org\apach
e\cordova\CordovaInterfaceImpl.java:202: error: cannot find symbol
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
                                                       ^
  symbol:   variable M
  location: class VERSION_CODES
C:\work\svn\jsim\rig\mobile\tmp\EhApp\platforms\android\CordovaLib\src\org\apach
e\cordova\CordovaInterfaceImpl.java:204: error: cannot find symbol
            int result = activity.checkSelfPermission(permission);
                                 ^
  symbol:   method checkSelfPermission(String)
  location: variable activity of type Activity
C:\work\svn\jsim\rig\mobile\tmp\EhApp\platforms\android\CordovaLib\src\org\apach
e\cordova\CordovaActivity.java:493: error: method does not override or implement
 a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors
:CordovaLib:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':CordovaLib:compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 14.024 secs
ERROR building one of the platforms: Error: cmd: Command failed with exit code 1

You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 1

**Comment by JohnRSim** [comment]
Resolved my issue

**Comment by matudelatower** [comment]
How?

**Comment by cicerohellmann** [comment]
I also want to know how.

**Comment by mmocny** [comment]
All: this is a very old demo that isn't maintained at all.

I'm not sure how this user resolved the issue, but I'm not sure its worth resolving :P

**Comment by cicerohellmann** [comment]
It is not because of the demo, it is happening in my own project. What I did was change my android project minsdkversion to 14,because, aparently, there was some libs that where using it as a minimum. And I removed some repeated installed sdk, more specificly facebook, that was trhowing me some errors after I fixed this. 

Resuming, lower your min sdk version to match the libs you are using and watch if you didnt installed some plugin twice, facebook, for exemple, wont detect that it is already installed and will reinstall itself and later it will throw errors saying you have two of the same lib in  your android proj.

Any doubts, please ask me because it's fresh, I just resolved this issue.
